#!/bin/env python3

"""
Python script that copies a ZeroNet instance to another drive

Usage:
copy-zeronet from to

Exit codes:
0 - all went well
1 - invalid arguments supplied
2 - No files were found to copy (check permissions?)
3 - DBus service already running (already copying something?)
4 - An error occurred while copying (also emitted as DBus signal "Failed")
5 - Copying was canceled by the user

DBus:
Service Name:
com.netrunner.zeronet.cockpit.copier

Signals (namespace com.netrunner.zeronet)

Progress - peridocially reported with the number of copied files and total amount
Finished - copying finished successfully
Failed - copying failed (argument "s" contains exception message)
"""

import dbus, dbus.service, dbus.exceptions
import sys
import os
import shutil
import math

try:
    from gi.repository import GLib
except ImportError:
    import glib as GLib

from time import sleep # FIXME

from dbus.mainloop.glib import DBusGMainLoop

src = ""
dest = ""
filesCount = 0

class DBusService(dbus.service.Object):
    def __init__(self, path):
        dbus.service.Object.__init__(self, dbus.SessionBus(), path)

    # TODO add getters for source, destination, perhaps even UUID
    # so we can query that if we didn't trigger the script ourself
    @dbus.service.method(dbus_interface="com.netrunner.zeronet",
                         in_signature="", out_signature="a{sv}")
    def Info(self):
        dict = dbus.Dictionary({
            dbus.String(u"fromPath"): src,
            dbus.String(u"toPath"): dest,
            dbus.String(u"filesCount"): filesCount
        },
        signature = dbus.Signature("sv")
        )
        return dict

    @dbus.service.method(dbus_interface="com.netrunner.zeronet",
                         in_signature="", out_signature="b")
    def Cancel(self):
        # not really an error?
        errorEncountered = True
        self.Finished(errorEncountered)
        # just exiting here causes a dbus error
        # but setting a "wasCanceled" variable and then exiting
        # in the copy loop doesn't seem to work
        sys.exit(5)

        return True

    @dbus.service.signal(dbus_interface="com.netrunner.zeronet")
    def Progress(self, processed, total):
        pass

    @dbus.service.signal(dbus_interface="com.netrunner.zeronet")
    def Finished(self, withError):
        pass

    @dbus.service.signal(dbus_interface="com.netrunner.zeronet")
    def Failure(self, path, errorString):
        pass


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Invalid arguments")
        sys.exit(1)

    src = sys.argv[1]
    dest = sys.argv[2]

    print("Copy stuff from", src, "to", dest)

    # Count total number of files for progress reporting
    files = []
    if os.path.isdir(src):
        for path, dirs, filenames in os.walk(src):
            files.extend(filenames)

    filesCount = len(files)

    if filesCount == 0:
        print("No files found to copy")
        sys.exit(2)

    DBusGMainLoop(set_as_default=True)
    mainloop = GLib.MainLoop()

    try:
        bus_name = dbus.service.BusName("com.netrunner.zeronet.cockpit.copier",
                                        bus = dbus.SessionBus(),
                                        do_not_queue = True)
    except dbus.exceptions.NameExistsException:
        print("DBus service is already running")
        sys.exit(3)

    dbusService = DBusService("/")

    print("Copying", filesCount, "from", src, "to", dest)

    processedCount = 0

    # Ensure we only report on dbus every percent, not every file, which spams the bus
    reportAfter = max(1, math.ceil(filesCount / 100))

    errorEncountered = False

    try:
        for path, dirs, filenames in os.walk(src):
            for directory in dirs:
                destDir = os.path.join(path.replace(src,dest), directory)
                if not os.path.exists(destDir):
                    os.makedirs(destDir)

            for sfile in filenames:
                srcFile = os.path.join(path, sfile)
                destFile = os.path.join(path.replace(src, dest), sfile)

                try:
                    # copyfile does not preserve permissions, we first want to make sure everything gets copied
                    shutil.copyfile(srcFile, destFile)
                except Exception as e:
                    dbusService.Failure(srcFile, str(e))
                    errorEncountered = True

                try:
                    shutil.chown(destFile, "zeronet", "zeronet")
                    os.chmod(destFile, 511) # 777
                except:
                    pass

                processedCount += 1

                if math.fmod(processedCount, reportAfter) == 0:
                    dbusService.Progress(processedCount, filesCount)
                    # Process events
                    mainloop.get_context().iteration(may_block = False)
                    #sleep(0.05) # FIXME Look like work is being done

    except Exception as e:
        print("Exception file copying", str(e))
        errorEncountered = True
        dbusService.Finished(errorEncountered)
        sys.exit(4)

    # Now transfer the mtime of the data folder over so "last used" is the same
    try:
        stinfo = os.stat(os.path.join(src, "data"))
        os.utime(os.path.join(dest, "data"), (stinfo.st_atime, stinfo.st_mtime))
    except Exception as e:
        print("Exception adjusting data mtime", str(e))

    print("Done copying")
    dbusService.Finished(errorEncountered)
    sys.exit(0)
